version: "2"
services:
  db:
    container_name: ware-house-database
    image: postgres:14.4-alpine
    user: root
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
        - user-pgdata:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
          max-file: "5"
          max-size: "10m"
    restart: always

  odoo:
    container_name: ware-house-app
    image: odoo:15
    user: root
    depends_on:
      - db
    networks:
      - postgres
    ports:
      - "${ODOO_PORT}:8069"
    tty: true
    command: -- --dev=reload
    #    command: odoo scaffold /mnt/extra-addons/custom_module
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      #- /etc/timezone:/etc/timezone:ro
      #- /etc/localtime:/etc/localtime:ro
      # - ./entrypoint.sh:/entrypoint.sh   # if you want to install additional Python packages, uncomment this line!
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
    restart: always # run as a service

  pgadmin:
    container_name: pgadmin4-ware-house
    image: dpage/pgadmin4
    user: root
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - db
    ports:
      - "${PGADMIN_PORT}:80"
    networks:
      - postgres
    restart: unless-stopped
volumes:
  user-pgdata:

networks:
  postgres:
    driver: bridge